// Use this file with the domconv-webkit tool update the Haskell webkit DOM bindings
#include "dom/Attr.idl"
#include "page/BarInfo.idl"
#include "fileapi/Blob.idl"
#include "dom/CDATASection.idl"
#include "dom/CharacterData.idl"
#include "dom/Comment.idl"
#include "page/Console.idl"
#include "css/CSSRule.idl"
#include "css/CSSRuleList.idl"
#include "css/CSSStyleDeclaration.idl"
#include "css/CSSStyleSheet.idl"
#include "css/CSSValue.idl"
#include "dom/Document.idl"
#include "dom/DocumentFragment.idl"
#include "dom/DocumentType.idl"
#include "loader/appcache/DOMApplicationCache.idl"
#include "dom/DOMImplementation.idl"
#include "plugins/DOMMimeType.idl"
#include "plugins/DOMMimeTypeArray.idl"
#include "plugins/DOMPlugin.idl"
#include "plugins/DOMPluginArray.idl"
#include "page/DOMSecurityPolicy.idl"
#include "page/DOMSelection.idl"
#include "html/DOMSettableTokenList.idl"
#include "dom/DOMStringList.idl"
#include "html/DOMTokenList.idl"
#include "page/DOMWindow.idl"
#include "dom/Element.idl"
#include "dom/EntityReference.idl"
#include "dom/Event.idl"
#include "dom/EventTarget.idl"
#include "fileapi/File.idl"
#include "fileapi/FileList.idl"
//Not supported properly in webkitgtk or domconv
//#include "Modules/gamepad/Gamepad.idl"
//#include "Modules/gamepad/GamepadList.idl"
#include "Modules/geolocation/Geolocation.idl"
#include "page/History.idl"
#include "html/HTMLAnchorElement.idl"
#include "html/HTMLAppletElement.idl"
#include "html/HTMLAreaElement.idl"
#include "html/HTMLBaseElement.idl"
#include "html/HTMLBaseFontElement.idl"
#include "html/HTMLBodyElement.idl"
#include "html/HTMLBRElement.idl"
#include "html/HTMLButtonElement.idl"
#include "html/HTMLCanvasElement.idl"
#include "html/HTMLCollection.idl"
#include "html/HTMLDetailsElement.idl"
#include "html/HTMLDirectoryElement.idl"
#include "html/HTMLDivElement.idl"
#include "html/HTMLDListElement.idl"
#include "html/HTMLDocument.idl"
#include "html/HTMLElement.idl"
#include "html/HTMLEmbedElement.idl"
#include "html/HTMLFieldSetElement.idl"
#include "html/HTMLFontElement.idl"
#include "html/HTMLFormElement.idl"
#include "html/HTMLFrameElement.idl"
#include "html/HTMLFrameSetElement.idl"
#include "html/HTMLHeadElement.idl"
#include "html/HTMLHeadingElement.idl"
#include "html/HTMLHRElement.idl"
#include "html/HTMLHtmlElement.idl"
#include "html/HTMLIFrameElement.idl"
#include "html/HTMLImageElement.idl"
#include "html/HTMLInputElement.idl"
#include "html/HTMLKeygenElement.idl"
#include "html/HTMLLabelElement.idl"
#include "html/HTMLLegendElement.idl"
#include "html/HTMLLIElement.idl"
#include "html/HTMLLinkElement.idl"
#include "html/HTMLMapElement.idl"
#include "html/HTMLMarqueeElement.idl"
#include "html/HTMLMediaElement.idl"
#include "html/HTMLAudioElement.idl"
#include "html/HTMLMenuElement.idl"
#include "html/HTMLMetaElement.idl"
#include "html/HTMLModElement.idl"
#include "html/HTMLObjectElement.idl"
#include "html/HTMLOListElement.idl"
#include "html/HTMLOptGroupElement.idl"
#include "html/HTMLOptionElement.idl"
#include "html/HTMLOptionsCollection.idl"
#include "html/HTMLParagraphElement.idl"
#include "html/HTMLParamElement.idl"
#include "html/HTMLPreElement.idl"
#include "html/HTMLQuoteElement.idl"
#include "html/HTMLScriptElement.idl"
#include "html/HTMLSelectElement.idl"
#include "html/HTMLStyleElement.idl"
#include "html/HTMLTableCaptionElement.idl"
#include "html/HTMLTableCellElement.idl"
#include "html/HTMLTableColElement.idl"
#include "html/HTMLTableElement.idl"
#include "html/HTMLTableRowElement.idl"
#include "html/HTMLTableSectionElement.idl"
#include "html/HTMLTextAreaElement.idl"
#include "html/HTMLTitleElement.idl"
#include "html/HTMLUListElement.idl"
#include "html/HTMLVideoElement.idl"
#include "dom/KeyboardEvent.idl"
#include "page/Location.idl"
#include "html/MediaError.idl"
#include "css/MediaList.idl"
#include "css/MediaQueryList.idl"
#include "page/MemoryInfo.idl"
#include "dom/MouseEvent.idl"
#include "dom/MessagePort.idl"
#include "dom/MutationEvent.idl"
#include "dom/NamedNodeMap.idl"
#include "page/Navigator.idl"
#include "dom/Node.idl"
#include "dom/NodeFilter.idl"
#include "dom/NodeIterator.idl"
#include "dom/NodeList.idl"
#include "dom/Notation.idl"
#include "dom/ProcessingInstruction.idl"
#include "dom/Range.idl"
#include "page/Screen.idl"
#include "css/StyleMedia.idl"
#include "css/StyleSheet.idl"
#include "css/StyleSheetList.idl"
#include "storage/Storage.idl"
#include "Modules/quota/StorageInfo.idl"
#include "dom/Text.idl"
#include "html/TimeRanges.idl"
#include "dom/TreeWalker.idl"
#include "html/ValidityState.idl"
#include "dom/UIEvent.idl"
#include "page/WebKitAnimation.idl"
#include "page/WebKitAnimationList.idl"
#include "dom/WebKitNamedFlow.idl"
#include "page/WebKitPoint.idl"
#include "xml/XMLHttpRequest.idl"
#include "xml/XPathExpression.idl"
#include "xml/XPathNSResolver.idl"
#include "xml/XPathResult.idl"
