#define ENABLE_BATTERY_STATUS 1
#define ENABLE_CANVAS_PATH 1
#define ENABLE_CSS_DEVICE_ADAPTATION 1
#define ENABLE_CSS_REGIONS 1
#define ENABLE_DATACUE_VALUE 1
#define ENABLE_ENCRYPTED_MEDIA 1
#define ENABLE_ENCRYPTED_MEDIA_V2 1
#define ENABLE_FULLSCREEN_API 1
#define ENABLE_INDIE_UI 1
#define ENABLE_INPUT_TYPE_COLOR 1
// #define ENABLE_IOS_TOUCH_EVENTS 1
// #define ENABLE_LEGACY_NOTIFICATIONS 1
#define ENABLE_MEDIA_STREAM 1
#define ENABLE_NAVIGATOR_HWCONCURRENCY 1
// #define ENABLE_NOTIFICATIONS 1
#define ENABLE_ORIENTATION_EVENTS 1
#define ENABLE_PERFORMANCE_TIMELINE 1
#define ENABLE_PICTURE_SIZES 1
#define ENABLE_PROXIMITY_EVENTS 1
#define ENABLE_REQUEST_ANIMATION_FRAME 1
#define ENABLE_RESOURCE_TIMING 1
#define ENABLE_TOUCH_EVENTS 1
#define ENABLE_USER_TIMING 1
#define ENABLE_VIBRATION 1
#define ENABLE_VIDEO 1
#define ENABLE_VIDEO_PRESENTATION_MODE 1
#define ENABLE_VIDEO_TRACK 1
#define ENABLE_WEBVTT_REGIONS 1
#define ENABLE_WEB_TIMING 1
//#define LANGUAGE_GOBJECT 1
#define LANGUAGE_JAVASCRIPT 1
//#define LANGUAGE_OBJECTIVE_C 1
//#define WTF_PLATFORM_IOS 1

// Use this file with the domconv-webkit tool update the Haskell webkit DOM bindings
module core {
// for a in `find /Users/hamish/build/webkitgtk-2.7.2/Source/WebCore -name '*.idl' | sed 's|.*/WebCore/\(.*/.*\.idl\)|\1|'`; do echo "#include \"$a\""; done
#include "crypto/CryptoKey.idl"
#include "crypto/CryptoKeyPair.idl"
#include "crypto/SubtleCrypto.idl"
#include "css/Counter.idl"
#include "css/CSSCharsetRule.idl"
#include "css/CSSFontFaceLoadEvent.idl"
#include "css/CSSFontFaceRule.idl"
#include "css/CSSImportRule.idl"
#include "css/CSSKeyframeRule.idl"
#include "css/CSSKeyframesRule.idl"
#include "css/CSSMediaRule.idl"
#include "css/CSSPageRule.idl"
#include "css/CSSPrimitiveValue.idl"
#include "css/CSSRule.idl"
#include "css/CSSRuleList.idl"
#include "css/CSSStyleDeclaration.idl"
#include "css/CSSStyleRule.idl"
#include "css/CSSStyleSheet.idl"
#include "css/CSSSupportsRule.idl"
#include "css/CSSUnknownRule.idl"
#include "css/CSSValue.idl"
#include "css/CSSValueList.idl"
#include "css/DOMWindowCSS.idl"
#include "css/FontLoader.idl"
#include "css/MediaList.idl"
#include "css/MediaQueryList.idl"
#include "css/MediaQueryListListener.idl"
#include "css/Rect.idl"
#include "css/RGBColor.idl"
#include "css/StyleMedia.idl"
#include "css/StyleSheet.idl"
#include "css/StyleSheetList.idl"
#include "css/WebKitCSSFilterValue.idl"
#include "css/WebKitCSSMatrix.idl"
#include "css/WebKitCSSRegionRule.idl"
#include "css/WebKitCSSTransformValue.idl"
#include "css/WebKitCSSViewportRule.idl"
#include "dom/AnimationEvent.idl"
#include "dom/Attr.idl"
#include "dom/AutocompleteErrorEvent.idl"
#include "dom/BeforeLoadEvent.idl"
#include "dom/BeforeUnloadEvent.idl"
#include "dom/CDATASection.idl"
#include "dom/CharacterData.idl"
#include "dom/ChildNode.idl"
#include "dom/ClientRect.idl"
#include "dom/ClientRectList.idl"
#include "dom/Comment.idl"
#include "dom/CompositionEvent.idl"
#include "dom/CustomEvent.idl"
#include "dom/DataTransfer.idl"
#include "dom/DataTransferItem.idl"
#include "dom/DataTransferItemList.idl"
#include "dom/DeviceMotionEvent.idl"
#include "dom/DeviceOrientationEvent.idl"
#include "dom/Document.idl"
#include "dom/DocumentFragment.idl"
#include "dom/DocumentType.idl"
#include "dom/DOMCoreException.idl"
#include "dom/DOMError.idl"
#include "dom/DOMImplementation.idl"
#include "dom/DOMNamedFlowCollection.idl"
#include "dom/DOMStringList.idl"
#include "dom/DOMStringMap.idl"
#include "dom/Element.idl"
#include "dom/Entity.idl"
#include "dom/EntityReference.idl"
#include "dom/ErrorEvent.idl"
#include "dom/Event.idl"
#include "dom/EventException.idl"
#include "dom/EventListener.idl"
#include "dom/EventTarget.idl"
#include "dom/FocusEvent.idl"
#include "dom/HashChangeEvent.idl"
#include "dom/KeyboardEvent.idl"
#include "dom/MessageChannel.idl"
#include "dom/MessageEvent.idl"
#include "dom/MessagePort.idl"
#include "dom/MouseEvent.idl"
#include "dom/MutationEvent.idl"
#include "dom/MutationObserver.idl"
#include "dom/MutationRecord.idl"
#include "dom/NamedNodeMap.idl"
#include "dom/Node.idl"
#include "dom/NodeFilter.idl"
#include "dom/NodeIterator.idl"
#include "dom/NodeList.idl"
#include "dom/OverflowEvent.idl"
#include "dom/PageTransitionEvent.idl"
#include "dom/PopStateEvent.idl"
#include "dom/ProcessingInstruction.idl"
#include "dom/ProgressEvent.idl"
#include "dom/Range.idl"
#include "dom/RangeException.idl"
#include "dom/RequestAnimationFrameCallback.idl"
#include "dom/SecurityPolicyViolationEvent.idl"
#include "dom/StringCallback.idl"
#include "dom/Text.idl"
#include "dom/TextEvent.idl"
#include "dom/Touch.idl"
#include "dom/TouchEvent.idl"
#include "dom/TouchList.idl"
#include "dom/TransitionEvent.idl"
#include "dom/TreeWalker.idl"
#include "dom/UIEvent.idl"
#include "dom/WebKitAnimationEvent.idl"
#include "dom/WebKitNamedFlow.idl"
#include "dom/WebKitTransitionEvent.idl"
#include "dom/WheelEvent.idl"
#include "fileapi/Blob.idl"
#include "fileapi/File.idl"
#include "fileapi/FileError.idl"
#include "fileapi/FileException.idl"
#include "fileapi/FileList.idl"
#include "fileapi/FileReader.idl"
#include "fileapi/FileReaderSync.idl"
#include "html/canvas/ANGLEInstancedArrays.idl"
#include "html/canvas/CanvasGradient.idl"
#include "html/canvas/CanvasPattern.idl"
#include "html/canvas/CanvasProxy.idl"
#include "html/canvas/CanvasRenderingContext.idl"
#include "html/canvas/CanvasRenderingContext2D.idl"
#include "html/canvas/DOMPath.idl"
#include "html/canvas/EXTBlendMinMax.idl"
#include "html/canvas/EXTFragDepth.idl"
#include "html/canvas/EXTShaderTextureLOD.idl"
#include "html/canvas/EXTsRGB.idl"
#include "html/canvas/EXTTextureFilterAnisotropic.idl"
#include "html/canvas/OESElementIndexUint.idl"
#include "html/canvas/OESStandardDerivatives.idl"
#include "html/canvas/OESTextureFloat.idl"
#include "html/canvas/OESTextureFloatLinear.idl"
#include "html/canvas/OESTextureHalfFloat.idl"
#include "html/canvas/OESTextureHalfFloatLinear.idl"
#include "html/canvas/OESVertexArrayObject.idl"
#include "html/canvas/WebGL2RenderingContext.idl"
#include "html/canvas/WebGLActiveInfo.idl"
#include "html/canvas/WebGLBuffer.idl"
#include "html/canvas/WebGLCompressedTextureATC.idl"
#include "html/canvas/WebGLCompressedTexturePVRTC.idl"
#include "html/canvas/WebGLCompressedTextureS3TC.idl"
#include "html/canvas/WebGLContextAttributes.idl"
#include "html/canvas/WebGLContextEvent.idl"
#include "html/canvas/WebGLDebugRendererInfo.idl"
#include "html/canvas/WebGLDebugShaders.idl"
#include "html/canvas/WebGLDepthTexture.idl"
#include "html/canvas/WebGLDrawBuffers.idl"
#include "html/canvas/WebGLFramebuffer.idl"
#include "html/canvas/WebGLLoseContext.idl"
#include "html/canvas/WebGLProgram.idl"
#include "html/canvas/WebGLQuery.idl"
#include "html/canvas/WebGLRenderbuffer.idl"
#include "html/canvas/WebGLRenderingContext.idl"
#include "html/canvas/WebGLRenderingContextBase.idl"
#include "html/canvas/WebGLSampler.idl"
#include "html/canvas/WebGLShader.idl"
#include "html/canvas/WebGLShaderPrecisionFormat.idl"
#include "html/canvas/WebGLSync.idl"
#include "html/canvas/WebGLTexture.idl"
#include "html/canvas/WebGLTransformFeedback.idl"
#include "html/canvas/WebGLUniformLocation.idl"
#include "html/canvas/WebGLVertexArrayObject.idl"
#include "html/canvas/WebGLVertexArrayObjectOES.idl"
#include "html/DOMFormData.idl"
#include "html/DOMSettableTokenList.idl"
#include "html/DOMTokenList.idl"
#include "html/DOMURL.idl"
#include "html/HTMLAllCollection.idl"
#include "html/HTMLAnchorElement.idl"
#include "html/HTMLAppletElement.idl"
#include "html/HTMLAreaElement.idl"
#include "html/HTMLAudioElement.idl"
#include "html/HTMLBaseElement.idl"
#include "html/HTMLBaseFontElement.idl"
#include "html/HTMLBodyElement.idl"
#include "html/HTMLBRElement.idl"
#include "html/HTMLButtonElement.idl"
#include "html/HTMLCanvasElement.idl"
#include "html/HTMLCollection.idl"
#include "html/HTMLDataListElement.idl"
#include "html/HTMLDetailsElement.idl"
#include "html/HTMLDirectoryElement.idl"
#include "html/HTMLDivElement.idl"
#include "html/HTMLDListElement.idl"
#include "html/HTMLDocument.idl"
#include "html/HTMLElement.idl"
#include "html/HTMLEmbedElement.idl"
#include "html/HTMLFieldSetElement.idl"
#include "html/HTMLFontElement.idl"
#include "html/HTMLFormControlsCollection.idl"
#include "html/HTMLFormElement.idl"
#include "html/HTMLFrameElement.idl"
#include "html/HTMLFrameSetElement.idl"
#include "html/HTMLHeadElement.idl"
#include "html/HTMLHeadingElement.idl"
#include "html/HTMLHRElement.idl"
#include "html/HTMLHtmlElement.idl"
#include "html/HTMLIFrameElement.idl"
#include "html/HTMLImageElement.idl"
#include "html/HTMLInputElement.idl"
#include "html/HTMLKeygenElement.idl"
#include "html/HTMLLabelElement.idl"
#include "html/HTMLLegendElement.idl"
#include "html/HTMLLIElement.idl"
#include "html/HTMLLinkElement.idl"
#include "html/HTMLMapElement.idl"
#include "html/HTMLMarqueeElement.idl"
#include "html/HTMLMediaElement.idl"
#include "html/HTMLMenuElement.idl"
#include "html/HTMLMetaElement.idl"
#include "html/HTMLMeterElement.idl"
#include "html/HTMLModElement.idl"
#include "html/HTMLObjectElement.idl"
#include "html/HTMLOListElement.idl"
#include "html/HTMLOptGroupElement.idl"
#include "html/HTMLOptionElement.idl"
#include "html/HTMLOptionsCollection.idl"
#include "html/HTMLOutputElement.idl"
#include "html/HTMLParagraphElement.idl"
#include "html/HTMLParamElement.idl"
#include "html/HTMLPreElement.idl"
#include "html/HTMLProgressElement.idl"
#include "html/HTMLQuoteElement.idl"
#include "html/HTMLScriptElement.idl"
#include "html/HTMLSelectElement.idl"
#include "html/HTMLSourceElement.idl"
#include "html/HTMLSpanElement.idl"
#include "html/HTMLStyleElement.idl"
#include "html/HTMLTableCaptionElement.idl"
#include "html/HTMLTableCellElement.idl"
#include "html/HTMLTableColElement.idl"
#include "html/HTMLTableElement.idl"
#include "html/HTMLTableRowElement.idl"
#include "html/HTMLTableSectionElement.idl"
#include "html/HTMLTemplateElement.idl"
#include "html/HTMLTextAreaElement.idl"
#include "html/HTMLTitleElement.idl"
#include "html/HTMLTrackElement.idl"
#include "html/HTMLUListElement.idl"
#include "html/HTMLUnknownElement.idl"
#include "html/HTMLVideoElement.idl"
#include "html/ImageData.idl"
#include "html/MediaController.idl"
#include "html/MediaError.idl"
#include "html/MediaKeyError.idl"
#include "html/MediaKeyEvent.idl"
#include "html/RadioNodeList.idl"
#include "html/TextMetrics.idl"
#include "html/TimeRanges.idl"
#include "html/track/AudioTrack.idl"
#include "html/track/AudioTrackList.idl"
#include "html/track/DataCue.idl"
#include "html/track/TextTrack.idl"
#include "html/track/TextTrackCue.idl"
#include "html/track/TextTrackCueList.idl"
#include "html/track/TextTrackList.idl"
#include "html/track/TrackEvent.idl"
#include "html/track/VideoTrack.idl"
#include "html/track/VideoTrackList.idl"
#include "html/track/VTTCue.idl"
#include "html/track/VTTRegion.idl"
#include "html/track/VTTRegionList.idl"
#include "html/URLUtils.idl"
#include "html/ValidityState.idl"
#include "html/VoidCallback.idl"
#include "inspector/CommandLineAPIHost.idl"
#include "inspector/InspectorFrontendHost.idl"
#include "inspector/ScriptProfile.idl"
#include "inspector/ScriptProfileNode.idl"
#include "loader/appcache/DOMApplicationCache.idl"
#include "Modules/airplay/WebKitPlaybackTargetAvailabilityEvent.idl"
#include "Modules/battery/BatteryManager.idl"
#include "Modules/battery/NavigatorBattery.idl"
#include "Modules/encryptedmedia/MediaKeyMessageEvent.idl"
#include "Modules/encryptedmedia/MediaKeyNeededEvent.idl"
#include "Modules/encryptedmedia/MediaKeys.idl"
#include "Modules/encryptedmedia/MediaKeySession.idl"
//#include "Modules/gamepad/deprecated/Gamepad.idl"
//#include "Modules/gamepad/deprecated/GamepadList.idl"
//#include "Modules/gamepad/deprecated/NavigatorGamepad.idl"
#include "Modules/gamepad/Gamepad.idl"
#include "Modules/gamepad/GamepadButton.idl"
#include "Modules/gamepad/GamepadEvent.idl"
#include "Modules/gamepad/NavigatorGamepad.idl"
#include "Modules/geolocation/Coordinates.idl"
#include "Modules/geolocation/Geolocation.idl"
#include "Modules/geolocation/Geoposition.idl"
#include "Modules/geolocation/NavigatorGeolocation.idl"
#include "Modules/geolocation/PositionCallback.idl"
#include "Modules/geolocation/PositionError.idl"
#include "Modules/geolocation/PositionErrorCallback.idl"
#include "Modules/indexeddb/DOMWindowIndexedDatabase.idl"
#include "Modules/indexeddb/IDBAny.idl"
#include "Modules/indexeddb/IDBCursor.idl"
#include "Modules/indexeddb/IDBCursorWithValue.idl"
#include "Modules/indexeddb/IDBDatabase.idl"
#include "Modules/indexeddb/IDBFactory.idl"
#include "Modules/indexeddb/IDBIndex.idl"
#include "Modules/indexeddb/IDBKeyRange.idl"
#include "Modules/indexeddb/IDBObjectStore.idl"
#include "Modules/indexeddb/IDBOpenDBRequest.idl"
#include "Modules/indexeddb/IDBRequest.idl"
#include "Modules/indexeddb/IDBTransaction.idl"
#include "Modules/indexeddb/IDBVersionChangeEvent.idl"
//#include "Modules/indexeddb/WorkerGlobalScopeIndexedDatabase.idl"
#include "Modules/indieui/UIRequestEvent.idl"
#include "Modules/mediacontrols/MediaControlsHost.idl"
#include "Modules/mediasource/AudioTrackMediaSource.idl"
#include "Modules/mediasource/DOMURLMediaSource.idl"
#include "Modules/mediasource/MediaSource.idl"
#include "Modules/mediasource/SourceBuffer.idl"
#include "Modules/mediasource/SourceBufferList.idl"
#include "Modules/mediasource/TextTrackMediaSource.idl"
#include "Modules/mediasource/VideoPlaybackQuality.idl"
#include "Modules/mediasource/VideoTrackMediaSource.idl"
#include "Modules/mediastream/AllAudioCapabilities.idl"
#include "Modules/mediastream/AllVideoCapabilities.idl"
#include "Modules/mediastream/AudioStreamTrack.idl"
#include "Modules/mediastream/CapabilityRange.idl"
#include "Modules/mediastream/DOMURLMediaStream.idl"
#include "Modules/mediastream/HTMLMediaElementMediaStream.idl"
#include "Modules/mediastream/MediaSourceStates.idl"
#include "Modules/mediastream/MediaStream.idl"
#include "Modules/mediastream/MediaStreamCapabilities.idl"
#include "Modules/mediastream/MediaStreamEvent.idl"
#include "Modules/mediastream/MediaStreamTrack.idl"
#include "Modules/mediastream/MediaStreamTrackEvent.idl"
#include "Modules/mediastream/MediaStreamTrackSourcesCallback.idl"
#include "Modules/mediastream/MediaTrackConstraint.idl"
#include "Modules/mediastream/MediaTrackConstraints.idl"
#include "Modules/mediastream/MediaTrackConstraintSet.idl"
#include "Modules/mediastream/NavigatorUserMedia.idl"
#include "Modules/mediastream/NavigatorUserMediaError.idl"
#include "Modules/mediastream/NavigatorUserMediaErrorCallback.idl"
#include "Modules/mediastream/NavigatorUserMediaSuccessCallback.idl"
#include "Modules/mediastream/RTCConfiguration.idl"
#include "Modules/mediastream/RTCDataChannel.idl"
#include "Modules/mediastream/RTCDataChannelEvent.idl"
#include "Modules/mediastream/RTCDTMFSender.idl"
#include "Modules/mediastream/RTCDTMFToneChangeEvent.idl"
#include "Modules/mediastream/RTCIceCandidate.idl"
#include "Modules/mediastream/RTCIceCandidateEvent.idl"
#include "Modules/mediastream/RTCIceServer.idl"
#include "Modules/mediastream/RTCPeerConnection.idl"
#include "Modules/mediastream/RTCPeerConnectionErrorCallback.idl"
#include "Modules/mediastream/RTCSessionDescription.idl"
#include "Modules/mediastream/RTCSessionDescriptionCallback.idl"
#include "Modules/mediastream/RTCStatsCallback.idl"
#include "Modules/mediastream/RTCStatsReport.idl"
#include "Modules/mediastream/RTCStatsResponse.idl"
#include "Modules/mediastream/SourceInfo.idl"
#include "Modules/mediastream/VideoStreamTrack.idl"
#include "Modules/navigatorcontentutils/NavigatorContentUtils.idl"
#include "Modules/notifications/DOMWindowNotifications.idl"
#include "Modules/notifications/Notification.idl"
#include "Modules/notifications/NotificationCenter.idl"
#include "Modules/notifications/NotificationPermissionCallback.idl"
#include "Modules/notifications/WorkerGlobalScopeNotifications.idl"
#include "Modules/plugins/QuickTimePluginReplacement.idl"
#include "Modules/proximity/DeviceProximityEvent.idl"
#include "Modules/quota/DOMWindowQuota.idl"
#include "Modules/quota/NavigatorStorageQuota.idl"
#include "Modules/quota/StorageErrorCallback.idl"
#include "Modules/quota/StorageInfo.idl"
#include "Modules/quota/StorageQuota.idl"
#include "Modules/quota/StorageQuotaCallback.idl"
#include "Modules/quota/StorageUsageCallback.idl"
#include "Modules/quota/WorkerNavigatorStorageQuota.idl"
#include "Modules/speech/DOMWindowSpeechSynthesis.idl"
#include "Modules/speech/SpeechSynthesis.idl"
#include "Modules/speech/SpeechSynthesisEvent.idl"
#include "Modules/speech/SpeechSynthesisUtterance.idl"
#include "Modules/speech/SpeechSynthesisVoice.idl"
#include "Modules/streams/ReadableStream.idl"
#include "Modules/vibration/NavigatorVibration.idl"
#include "Modules/webaudio/AnalyserNode.idl"
#include "Modules/webaudio/AudioBuffer.idl"
#include "Modules/webaudio/AudioBufferCallback.idl"
#include "Modules/webaudio/AudioBufferSourceNode.idl"
#include "Modules/webaudio/AudioContext.idl"
#include "Modules/webaudio/AudioDestinationNode.idl"
#include "Modules/webaudio/AudioListener.idl"
#include "Modules/webaudio/AudioNode.idl"
#include "Modules/webaudio/AudioParam.idl"
#include "Modules/webaudio/AudioProcessingEvent.idl"
#include "Modules/webaudio/BiquadFilterNode.idl"
#include "Modules/webaudio/ChannelMergerNode.idl"
#include "Modules/webaudio/ChannelSplitterNode.idl"
#include "Modules/webaudio/ConvolverNode.idl"
#include "Modules/webaudio/DelayNode.idl"
#include "Modules/webaudio/DynamicsCompressorNode.idl"
#include "Modules/webaudio/GainNode.idl"
#include "Modules/webaudio/MediaElementAudioSourceNode.idl"
#include "Modules/webaudio/MediaStreamAudioDestinationNode.idl"
#include "Modules/webaudio/MediaStreamAudioSourceNode.idl"
#include "Modules/webaudio/OfflineAudioCompletionEvent.idl"
#include "Modules/webaudio/OfflineAudioContext.idl"
#include "Modules/webaudio/OscillatorNode.idl"
#include "Modules/webaudio/PannerNode.idl"
#include "Modules/webaudio/PeriodicWave.idl"
#include "Modules/webaudio/ScriptProcessorNode.idl"
#include "Modules/webaudio/WaveShaperNode.idl"
#include "Modules/webdatabase/Database.idl"
#include "Modules/webdatabase/DatabaseCallback.idl"
#include "Modules/webdatabase/DOMWindowWebDatabase.idl"
#include "Modules/webdatabase/SQLError.idl"
#include "Modules/webdatabase/SQLException.idl"
#include "Modules/webdatabase/SQLResultSet.idl"
#include "Modules/webdatabase/SQLResultSetRowList.idl"
#include "Modules/webdatabase/SQLStatementCallback.idl"
#include "Modules/webdatabase/SQLStatementErrorCallback.idl"
#include "Modules/webdatabase/SQLTransaction.idl"
#include "Modules/webdatabase/SQLTransactionCallback.idl"
#include "Modules/webdatabase/SQLTransactionErrorCallback.idl"
#include "Modules/websockets/CloseEvent.idl"
#include "Modules/websockets/WebSocket.idl"
#include "page/AbstractView.idl"
#include "page/BarProp.idl"
#include "page/Crypto.idl"
#include "page/DOMSecurityPolicy.idl"
#include "page/DOMSelection.idl"
#include "page/DOMWindow.idl"
#include "page/EventSource.idl"
#include "page/History.idl"
#include "page/Location.idl"
#include "page/Navigator.idl"
#include "page/Performance.idl"
#include "page/PerformanceEntry.idl"
#include "page/PerformanceEntryList.idl"
#include "page/PerformanceMark.idl"
#include "page/PerformanceMeasure.idl"
#include "page/PerformanceNavigation.idl"
#include "page/PerformanceResourceTiming.idl"
#include "page/PerformanceTiming.idl"
#include "page/Screen.idl"
#include "page/UserMessageHandler.idl"
#include "page/UserMessageHandlersNamespace.idl"
#include "page/WebKitNamespace.idl"
#include "page/WebKitPoint.idl"
#include "page/WindowBase64.idl"
#include "page/WindowTimers.idl"
#include "page/WorkerNavigator.idl"
#include "plugins/DOMMimeType.idl"
#include "plugins/DOMMimeTypeArray.idl"
#include "plugins/DOMPlugin.idl"
#include "plugins/DOMPluginArray.idl"
#include "storage/Storage.idl"
#include "storage/StorageEvent.idl"
#include "svg/SVGAElement.idl"
#include "svg/SVGAltGlyphDefElement.idl"
#include "svg/SVGAltGlyphElement.idl"
#include "svg/SVGAltGlyphItemElement.idl"
#include "svg/SVGAngle.idl"
#include "svg/SVGAnimateColorElement.idl"
#include "svg/SVGAnimatedAngle.idl"
#include "svg/SVGAnimatedBoolean.idl"
#include "svg/SVGAnimatedEnumeration.idl"
#include "svg/SVGAnimatedInteger.idl"
#include "svg/SVGAnimatedLength.idl"
#include "svg/SVGAnimatedLengthList.idl"
#include "svg/SVGAnimatedNumber.idl"
#include "svg/SVGAnimatedNumberList.idl"
#include "svg/SVGAnimatedPreserveAspectRatio.idl"
#include "svg/SVGAnimatedRect.idl"
#include "svg/SVGAnimatedString.idl"
#include "svg/SVGAnimatedTransformList.idl"
#include "svg/SVGAnimateElement.idl"
#include "svg/SVGAnimateMotionElement.idl"
#include "svg/SVGAnimateTransformElement.idl"
#include "svg/SVGAnimationElement.idl"
#include "svg/SVGCircleElement.idl"
#include "svg/SVGClipPathElement.idl"
#include "svg/SVGColor.idl"
#include "svg/SVGComponentTransferFunctionElement.idl"
#include "svg/SVGCursorElement.idl"
#include "svg/SVGDefsElement.idl"
#include "svg/SVGDescElement.idl"
#include "svg/SVGDocument.idl"
#include "svg/SVGElement.idl"
#include "svg/SVGEllipseElement.idl"
#include "svg/SVGException.idl"
#include "svg/SVGExternalResourcesRequired.idl"
#include "svg/SVGFEBlendElement.idl"
#include "svg/SVGFEColorMatrixElement.idl"
#include "svg/SVGFEComponentTransferElement.idl"
#include "svg/SVGFECompositeElement.idl"
#include "svg/SVGFEConvolveMatrixElement.idl"
#include "svg/SVGFEDiffuseLightingElement.idl"
#include "svg/SVGFEDisplacementMapElement.idl"
#include "svg/SVGFEDistantLightElement.idl"
#include "svg/SVGFEDropShadowElement.idl"
#include "svg/SVGFEFloodElement.idl"
#include "svg/SVGFEFuncAElement.idl"
#include "svg/SVGFEFuncBElement.idl"
#include "svg/SVGFEFuncGElement.idl"
#include "svg/SVGFEFuncRElement.idl"
#include "svg/SVGFEGaussianBlurElement.idl"
#include "svg/SVGFEImageElement.idl"
#include "svg/SVGFEMergeElement.idl"
#include "svg/SVGFEMergeNodeElement.idl"
#include "svg/SVGFEMorphologyElement.idl"
#include "svg/SVGFEOffsetElement.idl"
#include "svg/SVGFEPointLightElement.idl"
#include "svg/SVGFESpecularLightingElement.idl"
#include "svg/SVGFESpotLightElement.idl"
#include "svg/SVGFETileElement.idl"
#include "svg/SVGFETurbulenceElement.idl"
#include "svg/SVGFilterElement.idl"
#include "svg/SVGFilterPrimitiveStandardAttributes.idl"
#include "svg/SVGFitToViewBox.idl"
#include "svg/SVGFontElement.idl"
#include "svg/SVGFontFaceElement.idl"
#include "svg/SVGFontFaceFormatElement.idl"
#include "svg/SVGFontFaceNameElement.idl"
#include "svg/SVGFontFaceSrcElement.idl"
#include "svg/SVGFontFaceUriElement.idl"
#include "svg/SVGForeignObjectElement.idl"
#include "svg/SVGGElement.idl"
#include "svg/SVGGlyphElement.idl"
#include "svg/SVGGlyphRefElement.idl"
#include "svg/SVGGradientElement.idl"
#include "svg/SVGGraphicsElement.idl"
#include "svg/SVGHKernElement.idl"
#include "svg/SVGImageElement.idl"
#include "svg/SVGLength.idl"
#include "svg/SVGLengthList.idl"
#include "svg/SVGLinearGradientElement.idl"
#include "svg/SVGLineElement.idl"
#include "svg/SVGMarkerElement.idl"
#include "svg/SVGMaskElement.idl"
#include "svg/SVGMatrix.idl"
#include "svg/SVGMetadataElement.idl"
#include "svg/SVGMissingGlyphElement.idl"
#include "svg/SVGMPathElement.idl"
#include "svg/SVGNumber.idl"
#include "svg/SVGNumberList.idl"
#include "svg/SVGPaint.idl"
#include "svg/SVGPathElement.idl"
#include "svg/SVGPathSeg.idl"
#include "svg/SVGPathSegArcAbs.idl"
#include "svg/SVGPathSegArcRel.idl"
#include "svg/SVGPathSegClosePath.idl"
#include "svg/SVGPathSegCurvetoCubicAbs.idl"
#include "svg/SVGPathSegCurvetoCubicRel.idl"
#include "svg/SVGPathSegCurvetoCubicSmoothAbs.idl"
#include "svg/SVGPathSegCurvetoCubicSmoothRel.idl"
#include "svg/SVGPathSegCurvetoQuadraticAbs.idl"
#include "svg/SVGPathSegCurvetoQuadraticRel.idl"
#include "svg/SVGPathSegCurvetoQuadraticSmoothAbs.idl"
#include "svg/SVGPathSegCurvetoQuadraticSmoothRel.idl"
#include "svg/SVGPathSegLinetoAbs.idl"
#include "svg/SVGPathSegLinetoHorizontalAbs.idl"
#include "svg/SVGPathSegLinetoHorizontalRel.idl"
#include "svg/SVGPathSegLinetoRel.idl"
#include "svg/SVGPathSegLinetoVerticalAbs.idl"
#include "svg/SVGPathSegLinetoVerticalRel.idl"
#include "svg/SVGPathSegList.idl"
#include "svg/SVGPathSegMovetoAbs.idl"
#include "svg/SVGPathSegMovetoRel.idl"
#include "svg/SVGPatternElement.idl"
#include "svg/SVGPoint.idl"
#include "svg/SVGPointList.idl"
#include "svg/SVGPolygonElement.idl"
#include "svg/SVGPolylineElement.idl"
#include "svg/SVGPreserveAspectRatio.idl"
#include "svg/SVGRadialGradientElement.idl"
#include "svg/SVGRect.idl"
#include "svg/SVGRectElement.idl"
#include "svg/SVGRenderingIntent.idl"
#include "svg/SVGScriptElement.idl"
#include "svg/SVGSetElement.idl"
#include "svg/SVGStopElement.idl"
#include "svg/SVGStringList.idl"
#include "svg/SVGStyleElement.idl"
#include "svg/SVGSVGElement.idl"
#include "svg/SVGSwitchElement.idl"
#include "svg/SVGSymbolElement.idl"
#include "svg/SVGTests.idl"
#include "svg/SVGTextContentElement.idl"
#include "svg/SVGTextElement.idl"
#include "svg/SVGTextPathElement.idl"
#include "svg/SVGTextPositioningElement.idl"
#include "svg/SVGTitleElement.idl"
#include "svg/SVGTransform.idl"
#include "svg/SVGTransformList.idl"
#include "svg/SVGTRefElement.idl"
#include "svg/SVGTSpanElement.idl"
#include "svg/SVGUnitTypes.idl"
#include "svg/SVGURIReference.idl"
#include "svg/SVGUseElement.idl"
#include "svg/SVGViewElement.idl"
#include "svg/SVGViewSpec.idl"
#include "svg/SVGVKernElement.idl"
#include "svg/SVGZoomAndPan.idl"
#include "svg/SVGZoomEvent.idl"
#include "testing/Internals.idl"
#include "testing/InternalSettings.idl"
#include "testing/MallocStatistics.idl"
#include "testing/MemoryInfo.idl"
#include "testing/TypeConversions.idl"
#include "workers/AbstractWorker.idl"
#include "workers/DedicatedWorkerGlobalScope.idl"
#include "workers/Worker.idl"
#include "workers/WorkerGlobalScope.idl"
#include "workers/WorkerLocation.idl"
#include "xml/DOMParser.idl"
#include "xml/XMLHttpRequest.idl"
#include "xml/XMLHttpRequestException.idl"
#include "xml/XMLHttpRequestProgressEvent.idl"
#include "xml/XMLHttpRequestUpload.idl"
#include "xml/XMLSerializer.idl"
#include "xml/XPathEvaluator.idl"
#include "xml/XPathException.idl"
#include "xml/XPathExpression.idl"
#include "xml/XPathNSResolver.idl"
#include "xml/XPathResult.idl"
#include "xml/XSLTProcessor.idl"
}
